### ISSUE TITLE
Does Zeit support .env already?

### ISSUE THREAD

**Issue by lorensr** [vadistic/now-dotenv#3]
This seems to indicate it does support .env?

![image](https://user-images.githubusercontent.com/251288/67716986-3a9f1380-f9a3-11e9-8232-742b740ef990.png)

https://zeit.co/docs/v2/serverless-functions/env-and-secrets/#providing-environment-variables

**Comment by vadistic** [comment]
Maybe, a bit?

You can reference variable present in environment - the possibility to use local .env file is actually new to me - need to check this out!

- There's definitely no way to reference specific .env file in now deploy. The `--env` as dotfile flag was removed in v2 and is present only in `now dev`. 
- You need to retype and reference all envs in now.json
- (This is dealbreaker for me) You still need to provide all envs as now-secrets if you want to use their GitHub integration. Otherwise you either need to deploy from your machine or commit secrets to git.

If this works, then you can probably commit your .env to git and use now secrets just for few, most vital keys. Idk, I think this cli provides better workflow.

There're specing new env system: https://github.com/zeit/now/issues/2613 I'm pretty sure they will make all of this obsolete in a month or few with some new shiny release.

Cheers!

**Comment by vadistic** [comment]
Ok - for some time there is nec env setup in vercel: https://vercel.com/blog/environment-variables-ui

I think it's time to deprecate this helper :)
